### PR TITLE
Feature 3DSv2

### PR DESCRIPTION
**Pull request by martinpotel**

### CODE REVIEW

**Comment by Zevran** [comment]
Resolves #3

**Comment by LupusVII** [comment]
Hi !
I've tried your pull request and it works fine until one point.
I think it's a bad idea to "control" the fields in the PaymentResponse, as we have done since the beginning.

When we look how Monetico retrieve its fields in the example, they just fetch all the $_POST array and work with it. Which means there is some vars we cannot really anticipate.

src/Payment/PaymentResponse.php - l.296
```
$fields = [
            'TPE' => $eptCode,
            'authentification' => $this->authenticationHash,
            'bincb' => $this->cardBIN,
            'brand' => $this->cardBrand,
            'code-retour' => $this->returnCode,
            'cvx' => $this->cardVerificationStatus,
            'date' => $this->datetime->format(self::DATETIME_FORMAT),
            'hpancb' => $this->cardHash,
            'ipclient' => $this->clientIp,
            'modepaiement' => $this->paymentMethod,
            'montant' => $this->amount,
            'numauto' => $this->authNumber,
            'originecb' => $this->cardCountry,
            'originetr' => $this->transactionCountry,
            'reference' => $this->reference,
            'texte-libre' => $this->description,
            'vld' => $this->cardExpirationDate,
            'version' => $version
        ];
```
replaced by
```
$fields = $_POST;
unset($fields['MAC']);
```

What do you think about that ?
Regards,
Julien

**Comment by Zevran** [comment]
Hi @LupusVII !

I agree with the fact that we can't really anticipate what Monetico gives us back, thanks to **"their beautiful api..."**. 
But It would be a terrible idea to accept the hole `$_POST` object in terms of security. The job is not finished yet so we will make sure we add a way to accept extra fields (but predefined) and enable or disable their validation.

Maybe like laravel validation (e.g. `nullable|string|size:12`) ? What do you think ?

Thanks for the time you invest on this !
Regards

**Comment by LupusVII** [comment]
Well. Actually, it was weird because I did all the tips & tricks because the initial bundle did not work but after trying again and again, it finally works... So +1 for this pull request.

**Pull request closed without merging**
